spring.application.name=agricultor-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db-cafetito:5432/DB_Cafetito?currentSchema=agricultor}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT:8082}
server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=agricultor
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

jwt.secret=${JWT_SECRET:cafetitoSecretKey_SUPER_SEGURA_2026_con_mas_de_256_bits_123456789}